Repository kwing25/Women-Who-ve-Changed-Tech, pull requests merged in 2022-10, with the labels that each got.

#52 Create SECURITY.md
  SECURITY.md
Labels: documentation, hacktoberfest, Priority: High

#44 Sophie germain jethet
  api/techwomen.json
Labels: Type: Enhancement, hacktoberfest, Status: Accepted

#54 Add 6 Tech Women to the List for the API
  api/techwomen.json
Labels: hacktoberfest, Status: Accepted, Status: In Progress

#58 Fixed previous branch deploy issues
  src/App.css
Labels: hacktoberfest, Status: Accepted, Type: Maintenance

#59 new entry to techwomen.json
  api/techwomen.json
Labels: hacktoberfest-accepted, Status: Accepted

#60 Uninstalled unused packages (issue #46)
  package-lock.json
  package.json
Labels: hacktoberfest, Status: Accepted, Status: In Progress, Type: Maintenance, dependencies
